import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#00285f",
        "primary-container": "#003d8a",
        "on-primary": "#ffffff",
        "on-primary-container": "#84acff",
        "on-primary-fixed": "#001a42",
        "on-primary-fixed-variant": "#004396",
        "primary-fixed": "#d8e2ff",
        "primary-fixed-dim": "#aec6ff",
        "secondary": "#3d5d9a",
        "secondary-container": "#9cbbfe",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#284a85",
        "on-secondary-fixed": "#001a41",
        "on-secondary-fixed-variant": "#234581",
        "secondary-fixed": "#d8e2ff",
        "secondary-fixed-dim": "#adc6ff",
        "tertiary": "#003120",
        "tertiary-container": "#004a32",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#62bd93",
        "on-tertiary-fixed": "#002114",
        "on-tertiary-fixed-variant": "#005237",
        "tertiary-fixed": "#99f5c8",
        "tertiary-fixed-dim": "#7dd8ad",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "surface": "#fcf8ff",
        "surface-dim": "#dad7f3",
        "surface-bright": "#fcf8ff",
        "surface-container": "#efecff",
        "surface-container-low": "#f5f2ff",
        "surface-container-lowest": "#ffffff",
        "surface-container-high": "#e8e5ff",
        "surface-container-highest": "#e2e0fc",
        "surface-variant": "#e2e0fc",
        "surface-tint": "#005ac4",
        "on-surface": "#1a1a2e",
        "on-surface-variant": "#434750",
        "on-background": "#1a1a2e",
        "background": "#fcf8ff",
        "outline": "#747781",
        "outline-variant": "#c4c6d1",
        "inverse-surface": "#2f2e43",
        "inverse-on-surface": "#f2efff",
        "inverse-primary": "#aec6ff",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
};
export default config;
